/* NodeDB-Lite C API — auto-generated by cbindgen. Do not edit. */

#ifndef NODEDB_LITE_H
#define NODEDB_LITE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Error codes returned by FFI functions.
 */
#define NodeDbNODEDB_OK 0

#define NodeDbNODEDB_ERR_NULL -1

#define NodeDbNODEDB_ERR_UTF8 -2

#define NodeDbNODEDB_ERR_FAILED -3

#define NodeDbNODEDB_ERR_NOT_FOUND -4

/**
 * Opaque handle to a NodeDB-Lite database.
 *
 * Created by `nodedb_open`, freed by `nodedb_close`.
 *
 * The `Arc<NodeDbLite>` is what the constructor returned, so the background
 * flush and compaction tasks live exactly as long as this handle does.
 *
 * `_tmpdir` is `Some` when the database was opened with the `:memory:` path.
 * The directory is deleted when the handle is dropped.
 */
typedef struct NodeDbNodeDbHandle NodeDbNodeDbHandle;

/**
 * Create a new ND sparse array.
 *
 * `schema_msgpack` — zerompk-encoded `ArraySchema`.
 * `dims_msgpack`   — reserved for future use; pass NULL / 0 today.
 *
 * Returns `NODEDB_OK` on success, `NODEDB_ERR_*` on failure.
 *
 * # Safety
 * All pointer parameters must be valid. `name` must be a null-terminated UTF-8 string.
 */
int32_t ndb_array_create(struct NodeDbNodeDbHandle *handle,
                         const char *name,
                         const uint8_t *schema_msgpack,
                         uintptr_t schema_len);

/**
 * Write a cell into array `name` at `coord`.
 *
 * `coord_msgpack`   — zerompk-encoded `Vec<CoordValue>`.
 * `payload_msgpack` — zerompk-encoded `Vec<CellValue>` (attribute values).
 * `valid_from_ms`   — valid-time lower bound (milliseconds since epoch).
 * `valid_until_ms`  — valid-time upper bound (`i64::MAX` = open-ended).
 *
 * # Safety
 * All pointer parameters must be valid. `name` must be a null-terminated UTF-8 string.
 */
int32_t ndb_array_put_cell(struct NodeDbNodeDbHandle *handle,
                           const char *name,
                           const uint8_t *coord_msgpack,
                           uintptr_t coord_len,
                           const uint8_t *payload_msgpack,
                           uintptr_t payload_len,
                           int64_t valid_from_ms,
                           int64_t valid_until_ms);

/**
 * Slice query: return all live cells whose coordinates fall within `ranges`.
 *
 * `ranges_msgpack` — zerompk-encoded `Vec<Option<DimRange>>`.
 * `as_of_system_ms` — system-time AS-OF (ignored when `has_as_of == 0`).
 * `has_as_of`       — set to 1 to use `as_of_system_ms`, 0 for current live snapshot.
 *
 * On success `*out_buf` points to a zerompk-encoded `Vec<CellPayload>`.
 * Caller must free with `nodedb_free_buf`.
 *
 * # Safety
 * All pointer parameters must be valid. `name` must be a null-terminated UTF-8 string.
 * `out_buf` and `out_len` must not be null.
 */
int32_t ndb_array_slice(struct NodeDbNodeDbHandle *handle,
                        const char *name,
                        const uint8_t *ranges_msgpack,
                        uintptr_t ranges_len,
                        int64_t as_of_system_ms,
                        uint8_t has_as_of,
                        uint8_t **out_buf,
                        uintptr_t *out_len);

/**
 * Read the most recent live payload for `coord` at or before `as_of_system_ms`.
 *
 * `coord_msgpack`   — zerompk-encoded `Vec<CoordValue>`.
 * `has_as_of`       — set to 1 to use `as_of_system_ms`, 0 for current live snapshot.
 *
 * On success and if a cell exists, `*out_buf` points to a zerompk-encoded
 * `CellPayload` (length > 0). If the cell does not exist, `*out_len` is 0
 * and `*out_buf` is NULL.
 * Caller must free with `nodedb_free_buf` when `*out_len > 0`.
 *
 * # Safety
 * All pointer parameters must be valid. `name` must be a null-terminated UTF-8 string.
 * `out_buf` and `out_len` must not be null.
 */
int32_t ndb_array_read_coord(struct NodeDbNodeDbHandle *handle,
                             const char *name,
                             const uint8_t *coord_msgpack,
                             uintptr_t coord_len,
                             int64_t as_of_system_ms,
                             uint8_t has_as_of,
                             uint8_t **out_buf,
                             uintptr_t *out_len);

/**
 * Soft-delete a cell by writing a tombstone at the current system time.
 *
 * `coord_msgpack` — zerompk-encoded `Vec<CoordValue>`.
 *
 * # Safety
 * All pointer parameters must be valid. `name` must be a null-terminated UTF-8 string.
 */
int32_t ndb_array_delete_cell(struct NodeDbNodeDbHandle *handle,
                              const char *name,
                              const uint8_t *coord_msgpack,
                              uintptr_t coord_len);

/**
 * GDPR erasure: permanently remove cell content at `coord`.
 *
 * `coord_msgpack` — zerompk-encoded `Vec<CoordValue>`.
 *
 * After this call `ndb_array_read_coord` returns empty for the coordinate
 * at any system time >= the erasure system timestamp.
 *
 * # Safety
 * All pointer parameters must be valid. `name` must be a null-terminated UTF-8 string.
 */
int32_t ndb_array_gdpr_erase_cell(struct NodeDbNodeDbHandle *handle,
                                  const char *name,
                                  const uint8_t *coord_msgpack,
                                  uintptr_t coord_len);

/**
 * Get a document by ID. Result written as JSON to `out_json`.
 *
 * Returns `NODEDB_ERR_NOT_FOUND` if the document doesn't exist.
 * `*out_json` is only written on success (`NODEDB_OK`). The caller must
 * free the returned string via `nodedb_free_string`.
 *
 * # Safety
 * All pointer parameters must be valid. `out_json` must not be null.
 */
int32_t nodedb_document_get(struct NodeDbNodeDbHandle *handle,
                            const char *collection,
                            const char *id,
                            char **out_json);

/**
 * Put (insert or update) a document. Body is a JSON string.
 *
 * If the JSON has no `"id"` field or it is empty, a UUIDv7 is auto-generated.
 * On success, if `out_id` is non-null, the assigned document ID is written to
 * `*out_id`. The caller must free it via `nodedb_free_string`.
 *
 * # Safety
 * All pointer parameters must be valid. `out_id` may be null (ID not returned).
 */
int32_t nodedb_document_put(struct NodeDbNodeDbHandle *handle,
                            const char *collection,
                            const char *json_body,
                            char **out_id);

/**
 * Delete a document by ID.
 *
 * # Safety
 * All pointer parameters must be valid.
 */
int32_t nodedb_document_delete(struct NodeDbNodeDbHandle *handle,
                               const char *collection,
                               const char *id);

/**
 * Full-text search (BM25). Results written as JSON array to `out_json`.
 *
 * `field` is the document field to search (e.g. `"body"`).
 * `*out_json` is only written on success. The caller must free via `nodedb_free_string`.
 *
 * # Safety
 * All pointer parameters must be valid. `out_json` must not be null.
 */
int32_t nodedb_text_search(struct NodeDbNodeDbHandle *handle,
                           const char *collection,
                           const char *field,
                           const char *query,
                           uintptr_t top_k,
                           char **out_json);

/**
 * Execute a SQL query. Results written as JSON to `out_json`.
 *
 * `*out_json` is only written on success. The caller must free via `nodedb_free_string`.
 *
 * # Safety
 * All pointer parameters must be valid. `out_json` must not be null.
 */
int32_t nodedb_execute_sql(struct NodeDbNodeDbHandle *handle, const char *sql, char **out_json);

/**
 * Insert a directed graph edge into `collection`.
 *
 * On success, writes the created edge id to `*out_edge_id` when it is non-null.
 * The caller frees it via `nodedb_free_string`, and passes it to
 * `nodedb_graph_delete_edge` to remove the edge.
 *
 * `*out_edge_id` is written only on success. Initialise it to NULL.
 *
 * An edge is keyed by `(from, to, edge_type)`. Re-inserting the same triple
 * returns the same id and creates no second edge.
 *
 * # Safety
 * All pointer parameters must be valid null-terminated UTF-8. `out_edge_id`
 * may be null (id not returned).
 */
int32_t nodedb_graph_insert_edge(struct NodeDbNodeDbHandle *handle,
                                 const char *collection,
                                 const char *from,
                                 const char *to,
                                 const char *edge_type,
                                 char **out_edge_id);

/**
 * Delete a graph edge by ID from `collection`.
 *
 * Edge ID format: length-prefixed form as returned by `graph_insert_edge`
 * Display (`"{src_len}:{src}|{label_len}:{label}|{dst_len}:{dst}|{seq}"`).
 * Take the id from `nodedb_graph_insert_edge`, never build the string by hand.
 *
 * Deletion is idempotent: an id naming no live edge returns `NODEDB_OK`.
 * A malformed id returns `NODEDB_ERR_FAILED`.
 *
 * # Safety
 * All pointer parameters must be valid null-terminated UTF-8.
 */
int32_t nodedb_graph_delete_edge(struct NodeDbNodeDbHandle *handle,
                                 const char *collection,
                                 const char *edge_id);

/**
 * Traverse the graph from a start node in `collection`. Results written as JSON to `out_json`.
 *
 * `*out_json` is only written on success. The caller must free via `nodedb_free_string`.
 *
 * # Safety
 * All pointer parameters must be valid UTF-8. `out_json` must not be null.
 */
int32_t nodedb_graph_traverse(struct NodeDbNodeDbHandle *handle,
                              const char *collection,
                              const char *start,
                              uint8_t depth,
                              char **out_json);

/**
 * Find the shortest path between two nodes in `collection`. Results written as JSON to `out_json`.
 *
 * Returns `NODEDB_OK` with a JSON array of node IDs, or `"null"` if no path exists.
 * `*out_json` is only written on success. The caller must free via `nodedb_free_string`.
 *
 * # Safety
 * All pointer parameters must be valid. `out_json` must not be null.
 */
int32_t nodedb_graph_shortest_path(struct NodeDbNodeDbHandle *handle,
                                   const char *collection,
                                   const char *from,
                                   const char *to,
                                   uint8_t max_depth,
                                   char **out_json);

/**
 * Insert a vector into a collection.
 *
 * # Safety
 * All pointer parameters must be valid. `embedding` must be non-null, properly
 * aligned for `f32`, and valid for exactly `dim` elements for the entire duration
 * of this call. No runtime length validation is possible; passing a mismatched
 * `dim` or a dangling pointer is immediate undefined behaviour.
 */
int32_t nodedb_vector_insert(struct NodeDbNodeDbHandle *handle,
                             const char *collection,
                             const char *id,
                             const float *embedding,
                             uintptr_t dim);

/**
 * Search for the k nearest vectors. Results are written as JSON to `out_json`.
 *
 * `*out_json` is only written on success. The caller must free via `nodedb_free_string`.
 *
 * # Safety
 * `query` must be non-null, properly aligned for `f32`, and valid for exactly `dim`
 * elements for the entire duration of this call. No runtime length validation is
 * possible; passing a mismatched `dim` or a dangling pointer is immediate undefined
 * behaviour. `out_json` must not be null.
 */
int32_t nodedb_vector_search(struct NodeDbNodeDbHandle *handle,
                             const char *collection,
                             const float *query,
                             uintptr_t dim,
                             uintptr_t k,
                             char **out_json);

/**
 * Delete a vector by ID.
 *
 * # Safety
 * All pointer parameters must be valid.
 */
int32_t nodedb_vector_delete(struct NodeDbNodeDbHandle *handle,
                             const char *collection,
                             const char *id);

/**
 * Generate a UUIDv7 (time-sortable, recommended for primary keys).
 *
 * # Safety
 * `out` must be a valid pointer to a `*mut c_char`.
 */
int32_t nodedb_generate_id(char **out);

/**
 * Generate an ID of the specified type.
 *
 * Supported types: "uuidv7", "uuidv4", "ulid", "cuid2", "nanoid".
 *
 * # Safety
 * `id_type` must be a valid null-terminated UTF-8 string. `out` must be a valid pointer.
 */
int32_t nodedb_generate_id_typed(const char *id_type, char **out);

/**
 * Free a string returned by nodedb_* functions.
 *
 * # Safety
 * `ptr` must be a string previously returned by a nodedb function, or NULL.
 */
void nodedb_free_string(char *ptr);

/**
 * Free a byte buffer returned by nodedb_* functions (e.g. `ndb_array_slice`).
 *
 * `len` must be the exact length originally written to `*out_len`.
 *
 * # Safety
 * `ptr` must be a buffer previously returned by a nodedb function, or NULL.
 */
void nodedb_free_buf(uint8_t *ptr, uintptr_t len);

/**
 * Open or create a NodeDB-Lite database at the given path.
 *
 * Returns an opaque handle on success, NULL on failure.
 * The caller must call `nodedb_close` to free the handle.
 *
 * Background flush and compaction start with the database, at the intervals
 * the resolved configuration specifies.
 *
 * # Safety
 * - `path` must be a valid null-terminated UTF-8 string.
 * - `passphrase` must be NULL or a valid null-terminated UTF-8 string.
 *
 * Encryption convention:
 * - `passphrase` is NULL and `path` is `":memory:"` → `Encryption::Plaintext` (volatile data, safe).
 * - `passphrase` is NULL and `path` is a real path → returns NULL (silent plaintext persistent
 *   storage is refused; pass an empty string to opt out explicitly).
 * - `passphrase` is `""` (empty string) → `Encryption::Plaintext` (explicit conscious opt-out).
 * - `passphrase` is a non-empty string → `Encryption::passphrase(passphrase)`.
 * - `passphrase` is non-NULL but invalid UTF-8 → returns NULL.
 */
struct NodeDbNodeDbHandle *nodedb_open(const char *path,
                                       const char *passphrase);

/**
 * Open or create a NodeDB-Lite database with an explicit memory budget.
 *
 * # Safety
 * - `path` must be a valid null-terminated UTF-8 string.
 * - `passphrase` must be NULL or a valid null-terminated UTF-8 string.
 *
 * See `nodedb_open` for the passphrase/encryption convention.
 * `memory_mb` of 0 uses the default memory budget.
 */
struct NodeDbNodeDbHandle *nodedb_open_with_config(const char *path,
                                                   uint64_t memory_mb,
                                                   const char *passphrase);

/**
 * Open a NodeDB-Lite database, **discarding the store if it cannot be read**.
 *
 * Every other open entry point refuses to open a damaged store and leaves it
 * untouched. This one renames it to `{path}.corrupt.{unix_secs}` and returns a
 * handle to a fresh, empty database in its place.
 *
 * The returned database contains none of the previous data. Any writes it
 * accepts diverge from the copy set aside, so this is only appropriate when
 * the caller has another source of truth to refill from — an Origin to
 * re-sync, or data that can be regenerated. If unsure, use `nodedb_open`: an
 * open that fails is recoverable, and a store that has been replaced is not.
 *
 * # Safety
 * - `path` must be a valid null-terminated UTF-8 string.
 * - `passphrase` must be NULL or a valid null-terminated UTF-8 string.
 *
 * See `nodedb_open` for the passphrase/encryption convention.
 * `memory_mb` of 0 uses the default memory budget.
 */
struct NodeDbNodeDbHandle *nodedb_open_discarding_corrupt_store(const char *path,
                                                                uint64_t memory_mb,
                                                                const char *passphrase);

/**
 * Close a NodeDB-Lite database and free the handle.
 *
 * # Safety
 * `handle` must be a token returned by `nodedb_open`, or NULL/0 (no-op).
 * The token is a `u64` id packed into a pointer-width integer; it is never
 * dereferenced as a raw pointer.
 */
void nodedb_close(struct NodeDbNodeDbHandle *handle);

/**
 * Flush all in-memory state to disk.
 *
 * # Safety
 * `handle` must be a valid pointer returned by `nodedb_open`.
 */
int32_t nodedb_flush(struct NodeDbNodeDbHandle *handle);

/**
 * Compact the backing store, reclaiming dead pages and truncating the file to
 * bound on-disk growth.
 *
 * The three `out_*` pointers receive the compaction outcome; any of them may
 * be NULL to ignore that field. On error they are left untouched.
 *
 * Returns `NODEDB_OK` on success, `NODEDB_ERR_NULL` if `handle` is NULL, or
 * `NODEDB_ERR_FAILED` on a compaction error.
 *
 * # Safety
 * `handle` must be a valid pointer returned by `nodedb_open`. Each non-NULL
 * `out_*` pointer must be writable and correctly aligned.
 */
int32_t nodedb_compact(struct NodeDbNodeDbHandle *handle,
                       uint64_t *out_reclaimed_pages,
                       uint32_t *out_segments_repacked,
                       uint64_t *out_file_bytes_freed);

/**
 * Start background CRDT sync to an Origin server.
 *
 * Connects via WebSocket to the given URL, authenticates with the JWT token,
 * and continuously pushes pending deltas / receives shape updates.
 * Runs forever in the background with auto-reconnect.
 *
 * Returns `NODEDB_OK` on successful launch (sync runs asynchronously).
 *
 * # Safety
 * `url` and `jwt_token` must be valid null-terminated UTF-8 strings.
 */
int32_t nodedb_start_sync(struct NodeDbNodeDbHandle *handle,
                          const char *url,
                          const char *jwt_token);

/**
 * Return the library version as a static string, e.g. `"0.1.0+ee9ccdd"`.
 *
 * Safe to call before any open; no allocation per call.
 * The returned pointer is owned by the library — do not free it.
 */
const char *nodedb_version(void);

/**
 * Return the ABI version as an integer.
 *
 * Bumped on breaking FFI changes. Bindings should compare this against their
 * compile-time expectation and refuse to run on mismatch.
 */
uint32_t nodedb_abi_version(void);

#endif  /* NODEDB_LITE_H */
